name: Deploy Homologacao

on:
  push:
    branches:
      - homologacao

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Baixando o codigo
        uses: actions/checkout@v4

      - name: Enviando para o HostGator (Pasta TESTE)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/smart/teste/
